### ISSUE TITLE
core/boxes/...widget1.php in the new modules line 209

### ISSUE THREAD

**Issue by DevTL1** [IAS-SYSTEMS-CSC/spring#178]
Warning: Declaration of manufacturewidget1::showBox($head = NULL, $contents = NULL) should be compatible with ModeleBoxes::showBox($head = NULL, $contents = NULL, $nooutput = 0) in /Users/devtl/Sites/IAS-Work/spring/portfolio/ifintech/v1/ierp/htdocs/custom/manufacture/core/boxes/manufacturewidget1.php on line 209

Warning: Declaration of fixedassetswidget1::showBox($head = NULL, $contents = NULL) should be compatible with ModeleBoxes::showBox($head = NULL, $contents = NULL, $nooutput = 0) in /Users/devtl/Sites/IAS-Work/spring/portfolio/ifintech/v1/ierp/htdocs/custom/fixedassets/core/boxes/fixedassetswidget1.php on line 209

Warning: Declaration of IHCMwidget1::showBox($head = NULL, $contents = NULL) should be compatible with ModeleBoxes::showBox($head = NULL, $contents = NULL, $nooutput = 0) in /Users/devtl/Sites/IAS-Work/spring/portfolio/ifintech/v1/ierp/htdocs/custom/ihcm/core/boxes/ihcmwidget1.php on line 209

Warning: Declaration of payablewidget1::showBox($head = NULL, $contents = NULL) should be compatible with ModeleBoxes::showBox($head = NULL, $contents = NULL, $nooutput = 0) in /Users/devtl/Sites/IAS-Work/spring/portfolio/ifintech/v1/ierp/htdocs/custom/payable/core/boxes/payablewidget1.php on line 209

**Comment by php-1** [comment]
fixed by heba ( tl1 )
