### ISSUE TITLE
KPI Agents List

### ISSUE THREAD

**Issue by DevTL1** [IAS-SYSTEMS-CSC/spring#183]
Fatal error: Uncaught Error: Class 'FormOther' not found in /Users/devtl/Sites/IAS-Work/spring/portfolio/ifintech/v1/ierp/htdocs/custom/ihcm/kpi/kpi_list.php:270 Stack trace: #0 {main} thrown in /Users/devtl/Sites/IAS-Work/spring/portfolio/ifintech/v1/ierp/htdocs/custom/ihcm/kpi/kpi_list.php on line 270

**Comment by hythamsoliman81** [comment]
Not an issue, the module yet completed. url just written but not physically created yet.
