### ISSUE TITLE
KPI Assign Agent

### ISSUE THREAD

**Issue by DevTL1** [IAS-SYSTEMS-CSC/spring#184]
Fatal error: Uncaught Error: Call to a member function getTypesKpiName() on null in /Users/devtl/Sites/IAS-Work/spring/portfolio/ifintech/v1/ierp/htdocs/custom/ihcm/kpi/kpi_assign.php:290 Stack trace: #0 {main} thrown in /Users/devtl/Sites/IAS-Work/spring/portfolio/ifintech/v1/ierp/htdocs/custom/ihcm/kpi/kpi_assign.php on line 290

**Comment by hythamsoliman81** [comment]
Not an issue, the module yet completed. url just written but not physically created yet.
