### ISSUE TITLE
warnings on account.php file 

### ISSUE THREAD

**Issue by DevTL1** [IAS-SYSTEMS-CSC/spring#217]
![snip 2018-01-14 20 17 29](https://user-images.githubusercontent.com/34707164/34918715-21a5c064-f968-11e7-8c22-179fb8ddc6eb.png)

**Comment by hythamsoliman81** [comment]
@DevTL1 advise if this issue is still opened, if so, please ask @php-2 to solve it, otherwise please close the issue with Justification.

**Comment by DevTL1** [comment]
Yes Still Opened

**Comment by DevTL1** [comment]
solved by php-3 Amira Ahmed
