### ISSUE TITLE
BUG: iHCM Module

### ISSUE THREAD

**Issue by hythamsoliman81** [IAS-SYSTEMS-CSC/spring#383]
Wherever the word "IHCM" appears at the application, it must show as "iHCM"
for example, main menu,  User permissions, etc ...

below few issues.

1- Assign KPI screen, drop down list for KPIs, should show only the approved KPIs and also should not yet expired ...

2- List of Assign, after press any of the IDs, it will show empty screen.

3- While editing KPI, and changing the description, and press save, this message will appear : 
Field 'kpi weight' is required
Please note KPI weight was already filled while screen load.

4- Screen layout for new KPI and edit KPI are different!

5- Training New and Edit are different layout.

6 - List of training, the field cost showing %

7- While editing item from Training Assign, it still show screen label as "New Training" and also will show empty screen!

8- Edit Social insurance will show empty screen!

9- User Relative Age should allow only numbers.

10- Assign Medical Insurance & List Assigned Medical links are giving a fatal error!

11- While open List User relative for editing any record, then apply no change and just press save, it will be showing negative values for Type relative & User relative gender

12- There is no User permissions for any of the screens under this module.

13- Default permissions for all records of the iHCM is enabled! while it should be created with disable status under default.

Please, review the whole module again. This is initial testing only.

**Comment by php-1** [comment]
Done all issues
