### ISSUE TITLE
Droplist user relative based on another droplist in ihcm (medical_insurance)

### ISSUE THREAD

**Issue by php-1** [IAS-SYSTEMS-CSC/spring#459]
Error when clicking on user parent : 
user_parent_id :5 is correct 
 but :-1: 
GET http://localhost/IAS-Work/spring/portfolio/ifintech/v1/ierp/htdocs/custom/ihcm/medical_insurance/ajax.php?userparentid=5 500 (Internal Server Error)

**Comment by php-3** [comment]
solved issue
