### ISSUE TITLE
BUG > iManufacture > Production line > new

### ISSUE THREAD

**Issue by ui-1** [IAS-SYSTEMS-CSC/spring#570]
![Uploading bug_productionline.png…]()

**Comment by hythamsoliman81** [comment]
the image was not attached. please resend it.

**Comment by ui-1** [comment]
![bug_productionline](https://user-images.githubusercontent.com/34981821/36070883-1f934ec6-0f0d-11e8-9787-69feb20aca13.png)

**Comment by php-1** [comment]
solve this issues
